### ISSUE TITLE
issue on bindable func

### ISSUE THREAD

**Issue by yildirimatcioglu** [manishkkatoch/SimpleTwoWayBindingIOS#14]
_self.addTarget(Selector, action: Selector{ [weak self] in self?.valueChanged() }, for: [.editingChanged, .valueChanged])
it gives "Cannot convert value of type '() -> ()?' to expected argument type 'String' " error

**Comment by thinium** [comment]
I ran into the same issue! You need to include the **Selector** magic in your project file:
https://github.com/manishkkatoch/SimpleTwoWayBindingIOS/tree/master/Sources/BlockBasedSelector

**Comment by manishkkatoch** [comment]
I'll be closing this issue as this is not a problem if one uses Cocoapod. please re-open if this is invalid.
